### ISSUE TITLE
Missing features?

### ISSUE THREAD

**Issue by ogreyesp** [ChrisTimperley/Wallace.jl#27]
Hi,
I have seen this project while searching at the Internet for doing evolutionary computation in Julia. I have read the description of Wallace, and it seems that it has implemented a lot of features, e.g. "Multiple objective optimisation: NSGA, NSGA-II, SPEA, SPEA2, VEGA, and more.", however, I am not able to find them in Wallace. These features are already included, or they are expected to be included in the future?

Best regard
Oscar

**Comment by ChrisTimperley** [comment]
Hi Oscar,

I'm afraid that Wallace is no longer actively maintained. The source code is just intended to be a starting point for others developing evolutionary computation frameworks in Julia, and to demonstrate the concept of using run-time meta-programming to improve performance.

Thanks for your interest,
Chris
